Dockerfile
README.md
src/service/config.ts
src/service/gateways/hitbtc.ts
src/service/main.ts
src/service/persister.ts

From now on, Docker is going to be the preferred way of deploying and running due to the reproducibility and ease of deployment. I have updated the docs to give an in-depth tutorial of how to set up tribeca using the new method. I'm not 100% satisfied with the deployment process, copying the Dockerfile and all, but that seems on Docker for making it hard to configure at runtime.

Config changes

---

README.md
sample-dev-tribeca.json
sample-prod-tribeca.json

Documentation changes to restore the manual installation process for those choosing not to use Docker.

Restore README and introduce JSON files for manual install

---

Dockerfile
sample-dev-tribeca.json
sample-prod-tribeca.json
src/common/models.ts
src/service/backtest.ts
src/service/broker.ts
src/service/main.ts
src/service/markettrades.ts
src/service/persister.ts
src/service/position-management.ts

When using multiple instances of tribeca and the same DB, the Quoting Parameters would get stomped over. Also gave me a chance to refactor.

Multicurrency Persistence

---

package.json

fix issue #36

---

src/admin/client.ts
src/admin/pair.ts
src/common/messaging.ts
src/common/models.ts
src/service/backtest.ts
src/service/broker.ts
src/service/gateways/bitfinex.ts
src/service/gateways/coinbase-api.ts
src/service/gateways/coinbase.ts
src/service/gateways/hitbtc.ts
src/service/gateways/nullgw.ts
src/service/gateways/okcoin.ts
src/service/interfaces.ts
src/service/main.ts
src/static/index.html
tsd.json

Adds cancel-all functionality now available on Coinbase. Exposed as a red button in the UI.

Cancel all open orders

---

Dockerfile
README.md

This is so I can start using ES6 goodness

Upgrade node version in README and dockerfile

---

Gruntfile.js
src/admin/trades.ts
src/common/models.ts
src/service/broker.ts
src/service/gateways/nullgw.ts
typings.json

Show and save trade liquidity in the UI, store it in the DB. Also move back to ES5 for the UI since ES6 doesn't work well on iPhone browsers.

Trades liquidity

---

src/admin/position.ts
src/common/models.ts
src/service/broker.ts
src/static/index.html

After this PR it looks like (for example):
Please feel free to request any modification to make this PR match your expectations.

Added display of quoteValue.

---

src/admin/messages.ts

Hello,
this small css modification hopes to fix #25 
but im not sure cos looks like really the code is trying to hide the grid header (if the header is correctly  hidden then may be OK to have there those original 50px, but for me the header is visible so i added some px).

Fixed height of messageOptions.

---

Dockerfile
README.md
package.json

Hardcoded typings versions to avoid breaking changes in typings 1.0

---

LICENSE.md

add ISC acronym

---

src/service/gateways/coinbase.ts

Coinbase adding LTC produces an error upon startup, this is the fix.

Added fix for Coinbase support of LTC

---

src/admin/market-trades.ts
src/admin/messages.ts
src/admin/orderlist.ts
src/admin/shared_directives.ts
src/admin/trades.ts
src/common/models.ts
src/service/broker.ts
src/service/gateways/coinbase.ts
src/service/gateways/hitbtc.ts
src/service/gateways/nullgw.ts
src/service/gateways/okcoin.ts
src/service/main.ts
src/service/market-filtration.ts
src/service/persister.ts
src/service/quoter.ts
src/service/utils.ts
src/service/web.ts
src/static/index.html

A bunch of changes I've made on my personal branch a while back:
- Re-layout the UI to show more details about trades
- Better handle bursts of market updates
- Show 25 levels of depth, rate limit the updates
- Performance improvements to the grid, including only showing orders manually entered and not from quotes.

Quality of Life improvements

---

Dockerfile
README.md
src/admin/market-quoting.ts
src/admin/market-trades.ts
src/common/models.ts
src/service/backtest.ts
src/service/broker.ts
src/service/fair-value.ts
src/service/gateways/bitfinex.ts
src/service/gateways/coinbase-api.ts
src/service/gateways/coinbase.ts
src/service/gateways/hitbtc.ts
src/service/gateways/nullgw.ts
src/service/gateways/okcoin.ts
src/service/interfaces.ts
src/service/main.ts
src/service/market-filtration.ts
src/service/markettrades.ts
src/service/position-management.ts
src/service/quoting-engine.ts
src/service/quoting-styles/helpers.ts
src/service/quoting-styles/mid-market.ts
src/service/quoting-styles/style-registry.ts
src/service/quoting-styles/top-join.ts
src/service/utils.ts
src/static/index.html

Addresses #26
This finds and replaces all places where prices of 2 decimal place precision are used, so now you are able to quote in sub hundredths of quote currency denominations. I.E. tribeca now can trade DOGE/USD which is trading at about $0.000523.
The information about tick increments are taken directly from the exchange's product download and the configuration TradedPair is validated against that list.

Any currency pair trading

---

src/common/models.ts
src/service/backtest.ts
src/service/broker.ts
src/service/gateways/bitfinex.ts
src/service/gateways/coinbase.ts
src/service/gateways/hitbtc.ts
src/service/gateways/nullgw.ts
src/service/gateways/okcoin.ts
src/service/interfaces.ts

I wanted to get rid of some more of the duplication and object allocations around order sending. This is still part of my work to address #97

Order refactoring

---

src/service/fair-value.ts

Fix issue with FV rounding when using sub hundreths currencies

---

src/service/backtest.ts
src/service/broker.ts
src/service/main.ts
src/service/persister.ts
src/service/quoting-engine.ts

Includes many more performance improvements. The "is quote different" check was broken, and always thought quotes changed which resulted in a lot of useless work. Batching persistence operations.

More perf improvements

---

src/common/models.ts
src/service/active-state.ts
src/service/backtest.ts
src/service/broker.ts
src/service/config.ts
src/service/fair-value.ts
src/service/gateways/bitfinex.ts
src/service/gateways/coinbase-api.ts
src/service/gateways/coinbase.ts
src/service/gateways/hitbtc.ts
src/service/gateways/okcoin.ts
src/service/main.ts
src/service/markettrades.ts
src/service/persister.ts
src/service/position-management.ts
src/service/promises.ts
src/service/quote-sender.ts
src/service/quoter.ts
src/service/quoting-engine.ts
src/service/quoting-parameters.ts
src/service/statistics.ts
src/service/utils.ts
src/service/websocket.ts

1. Got rid of moment.js in the service. Creation of moments was showing up as a large CPU drag on the system.
2. Added the missing Promises.ts file missed, #107 
3. Don't log to tribeca.log, only stdout (pipe to a file if you want that)
4. Don't error out when re-issuing to a done order within 5 seconds.

More performance improvements

---

src/service/logging.ts

Missed this file. I need to get better about running `git status`...

Add missing logging file

---

src/service/main.ts

assign initial value to exitingEvent

---

src/service/gateways/hitbtc.ts
src/service/websocket.ts

Just trying to keep this implementation up to date...

Use the min tick in hitbtc, and use the new websocket client

---

README.md
env
sample-dev-tribeca.json
sample-prod-tribeca.json
src/service/broker.ts
src/service/config.ts
src/service/main.ts

Addresses #111 
Please don't use this in production.

All orders
